# Generated by Django 3.0.4 on 2020-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproject',
            name='pdf_docs',
            field=models.FileField(blank=True, null=True, upload_to='pdf docs'),
        ),
    ]
